export { TrainerPage } from './components/TrainerPage'
export { useRangeQuery } from './hooks/use-range-query'
export { loadProvider, resolveCorrectAction } from './lib/range-loader'
export { generateSmartSpot, generateSpot } from './lib/spot-generator'
export { hasMixedStrategies, parseChartKey, enumerateCharts } from './lib/chart-utils'
export { buildSpotTypeKey, buildSpotTypeKeyFromSpot } from './lib/spot-type-key'
export { evToQualityScore, estimateEvLoss, updateMastery, createInitialMastery } from './lib/sm2'
export { recordSpotResult, getMasteryRecordsForProvider, getMasteryRecord } from './lib/mastery-persistence'
export type { Spot, SpotResult, TrainerPhase, SessionStats, SpotFilters, TrainerMode, ProviderCharts } from './types'
